---

- name: Create seafile-net network
  docker_network:
    name: seafile-net

- name: run db container
  docker_container:
    name: seafile-mysql
    image: mariadb:10.1
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "db_dev"  # Requested, set the root's password of MySQL service.
      MYSQL_LOG_CONSOLE: "true"
    volumes:
      - /opt/seafile-mysql/db:/var/lib/mysql
    networks:
      - name: seafile-net

- name: run memcached container
  docker_container:
    name: seafile-memcached
    image: memcached:1.5.6
    state: started
    restart_policy: always
    entrypoint: memcached -m 256
    networks:
      - name: seafile-net

- name: run seafile container
  docker_container:
    name: seafile
    image: seafileltd/seafile-mc:latest
    state: started
    restart_policy: always
    ports:
      - "8080:80"
      - "8000:8000"
      - "8082:8082"
#     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - /opt/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    env:
      DB_HOST: "seafile-mysql"
      DB_ROOT_PASSWD: "db_dev"  # Requested, the value shuold be root's password of MySQL service.
      SEAFILE_ADMIN_EMAIL: "me@example.com" # Specifies Seafile admin user, default is 'me@example.com'.
      SEAFILE_ADMIN_PASSWORD: "asecret"     # Specifies Seafile admin password, default is 'asecret'.
      SEAFILE_SERVER_LETSENCRYPT: "false"   # Whether to use https or not.
      SEAFILE_SERVER_HOSTNAME: "{{ seafile_host }}" # Specifies your host name if https is enabled.
    networks:
      - name: seafile-net