---
    
- hosts: kampos
  remote_user: root
  become: no
  roles: 
    - { role: common,  tags: common }
    - { role: docker,  tags: docker }
    - { role: nginx,   tags: nginx  }
    - { role: deploy,  tags: deploy }